begin;
create extension if not exists pgtap with schema extensions;
set local search_path=public,extensions;
select no_plan();
insert into auth.users(id,email) values('00000000-0000-0000-0000-00000000fa01','financial-year@test.local');
update profiles set role='admin' where user_id='00000000-0000-0000-0000-00000000fa01';
insert into account_heads(code,name,account_type,is_cash_bank) values
 (83001,'Year cash','asset',true),(83002,'Year income','income',false),
 (83003,'Year expense','expense',false),(83004,'Retained earnings','equity',false);
select set_config('request.jwt.claim.sub','00000000-0000-0000-0000-00000000fa01',true);
select set_config('request.jwt.claims','{"sub":"00000000-0000-0000-0000-00000000fa01","role":"authenticated"}',true);
set local role authenticated;
select lives_ok($$select create_financial_year(1990)$$,'admin creates financial year');
select is((select starts_on from financial_years where start_year=1990),'1990-04-01'::date,'year begins April 1');
select is((select ends_on from financial_years where start_year=1990),'1991-03-31'::date,'year ends March 31');
select throws_ok($$select create_voucher(1,'1989-12-31',83002,'missing year',1,83001,gen_random_uuid())$$,'P0001','Create financial year 1989-90 before posting','unconfigured date rejected');
select lives_ok($$select create_voucher(1,'1990-04-01',83002,'first day',100,83001,gen_random_uuid())$$,'first day accepted');
select lives_ok($$select create_voucher(2,'1991-03-31',83003,'last day',30,83001,gen_random_uuid())$$,'last day accepted');
select is((select net_result from financial_year_summary(1990)),70::numeric,'preview shows profit');
select throws_ok($$select close_financial_year(1990,83001)$$,'P0001','Select an equity account for retained earnings','cash cannot be retained earnings');
select lives_ok($$select close_financial_year(1990,83004)$$,'close posts transfer and locks year');
select ok((select closed_at is not null from financial_years where start_year=1990),'year is locked');
select is((select sum(credit-debit) from daybook where head_code=83002),0::numeric,'income closes to zero');
select is((select sum(debit-credit) from daybook where head_code=83003),0::numeric,'expense closes to zero');
select is((select sum(credit-debit) from daybook where head_code=83004),70::numeric,'profit transferred to equity');
select is((select sum(debit-credit) from daybook where head_code=83001),70::numeric,'cash remains unchanged');
select is((select net_result from financial_year_summary(1990)),70::numeric,'closed-year summary retains operating result');
select ok(exists(select 1 from financial_years where start_year=1991),'next year created');
select is((select balance from rpt_ledger(83001,'1991-04-01','1992-03-31') where row_kind='opening'),-70::numeric,'next year carries cash opening without duplicate entries');
select lives_ok($$select close_financial_year(1990,83004)$$,'repeated close is idempotent');
select is((select count(*)::integer from journals where kind='year_closing' and entry_date='1991-03-31'),1,'only one closing journal');
select throws_ok($$select create_voucher(1,'1990-06-01',83002,'locked',10,83001,gen_random_uuid())$$,'P0001','Financial year 1990-91 is closed','closed-year posting blocked');
select throws_ok($$select cancel_voucher((select id from vouchers where narration='first day'),'cancel closed')$$,'P0001','Financial year 1990-91 is closed','closed-year cancellation blocked');
select throws_ok($$select reverse_journal((select closing_journal_id from financial_years where start_year=1990),'1991-04-01','bypass')$$,'P0001','Reopen the financial year to reverse its closing entry','closing cannot be reversed directly');
select throws_ok($$select create_financial_year(1989)$$,'P0001','Cannot create a financial year before a closed year','cannot add a backdated year behind a closure');
select lives_ok($$select close_financial_year(1991,83004)$$,'empty next year closes without a journal');
select throws_ok($$select reopen_financial_year(1990,'correction')$$,'P0001','Reopen later closed years first','reopen order enforced');
select lives_ok($$select reopen_financial_year(1991,'allow correction')$$,'reopen latest year');
select lives_ok($$select reopen_financial_year(1990,'correct old entries')$$,'reopen reverses closing');
select is((select sum(credit-debit) from daybook where head_code=83004),0::numeric,'reopen removes equity transfer');
select is((select sum(credit-debit) from daybook where head_code=83002),100::numeric,'reopen restores income balance');
select is((select count(*)::integer from financial_year_reopen_log where start_year=1990),1,'reopening audited');
select lives_ok($$select close_financial_year(1990,83004)$$,'reclosed year recomputes transfer');
select is((select sum(credit-debit) from daybook where head_code=83004),70::numeric,'reclosing does not double retained earnings');
select lives_ok($$select create_financial_year(2100)$$,'future year can be configured');
select throws_ok($$select close_financial_year(2100,83004)$$,'P0001','The financial year has not ended yet','cannot close future year');
select lives_ok($$set constraints all immediate$$,'all year-end journals balance at commit');
select ok(not has_table_privilege('authenticated','financial_years','UPDATE'),'clients cannot bypass year locking directly');
select * from finish();
rollback;
