-- Merchant Accounts: core schema.
-- Legacy source (Azure SQL, VB app) -> new table:
--   MAS_SETTINGS -> company_settings   MAS_HEADS   -> account_heads
--   MAS_CUSTMR   -> customers          TRA_VOUCHTRN -> vouchers
--   TRA_DAYBOOK  -> daybook            Users        -> auth.users + profiles

create extension if not exists pg_trgm with schema extensions;

-- ---------------------------------------------------------------------------
-- Tables
-- ---------------------------------------------------------------------------

create table public.company_settings (
  id         boolean primary key default true check (id),  -- single row
  name       text not null default '',
  place      text not null default '',
  phone      text,
  gstin      text,
  updated_at timestamptz not null default now()
);
insert into public.company_settings default values;

create table public.account_heads (
  code       integer primary key check (code > 0),
  name       text not null check (length(trim(name)) > 0),
  kind       text,               -- legacy CKORC (meaning to be confirmed)
  group_type text,               -- legacy CBORP (P&L / balance sheet grouping, to be confirmed)
  ms_code    integer not null default 0,
  ss_code    integer not null default 0,
  is_auto    boolean not null default false,
  created_at timestamptz not null default now()
);
create index account_heads_name_idx on public.account_heads (name);

create table public.customers (
  code       integer primary key check (code > 0),
  salutation text,
  name       text not null check (length(trim(name)) > 0),
  addr1      text,
  addr2      text,
  addr3      text,
  addr4      text,
  phone      text,
  aadhaar    text,
  pan        text,
  id_type    text,
  id_no      text,
  photo_path text,               -- object key in storage bucket 'customer-photos'
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index customers_name_trgm_idx on public.customers using gin (name extensions.gin_trgm_ops);

create table public.vouchers (
  id            bigint generated always as identity primary key,
  voucher_type  smallint not null check (voucher_type in (1, 2)),  -- 1 receipt, 2 payment (legacy NRECPAY)
  voucher_no    integer not null check (voucher_no > 0),
  voucher_date  date not null,
  head_code     integer not null references public.account_heads (code),
  description   text not null default '',
  amount        numeric(14, 2) not null check (amount >= 0),       -- create_voucher enforces > 0; legacy rows may be 0
  branch        smallint not null default 2,
  cancelled_at  timestamptz,
  cancelled_by  uuid references auth.users (id),
  cancel_reason text,
  created_by    uuid default auth.uid() references auth.users (id),
  created_at    timestamptz not null default now(),
  unique (voucher_type, voucher_no)
);
create index vouchers_head_date_idx on public.vouchers (head_code, voucher_date);
create index vouchers_date_idx on public.vouchers (voucher_date);

-- Next voucher number per type. Row lock on update serialises concurrent callers.
create table public.voucher_counters (
  voucher_type smallint primary key check (voucher_type in (1, 2)),
  last_no      integer not null default 0 check (last_no >= 0)
);
insert into public.voucher_counters (voucher_type) values (1), (2);

create table public.daybook (
  id          bigint generated always as identity primary key,
  head_code   integer not null references public.account_heads (code),
  voucher_ref text,
  tran_date   date,              -- legacy rows with null date count as opening balance
  debit       numeric(14, 2) not null default 0 check (debit >= 0),
  credit      numeric(14, 2) not null default 0 check (credit >= 0),
  narration   text,
  is_auto     boolean not null default false,  -- true = generated by day book posting
  created_at  timestamptz not null default now()
);
create index daybook_date_idx on public.daybook (tran_date);
create index daybook_head_date_idx on public.daybook (head_code, tran_date);

create table public.profiles (
  user_id    uuid primary key references auth.users (id) on delete cascade,
  username   text unique,
  full_name  text,
  role       text not null default 'viewer' check (role in ('admin', 'accountant', 'viewer')),
  is_active  boolean not null default true,
  created_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- Helpers
-- ---------------------------------------------------------------------------

-- Role of the calling user, or null when not signed in / inactive.
create function public.app_role()
returns text
language sql
stable
security definer
set search_path = ''
as $$
  select p.role from public.profiles p where p.user_id = auth.uid() and p.is_active
$$;

-- Create a profile for every new auth user. The very first user becomes admin
-- (sign-ups are disabled, so the first user is created by the operator).
create function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (user_id, username, full_name, role)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'username', new.email),
    new.raw_user_meta_data ->> 'full_name',
    case when exists (select 1 from public.profiles) then 'viewer' else 'admin' end
  );
  return new;
end
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

create function public.touch_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at := now();
  return new;
end
$$;

create trigger customers_touch before update on public.customers
  for each row execute function public.touch_updated_at();
create trigger company_settings_touch before update on public.company_settings
  for each row execute function public.touch_updated_at();

-- ---------------------------------------------------------------------------
-- Voucher RPCs (vouchers are never written directly by clients)
-- ---------------------------------------------------------------------------

create function public.create_voucher(
  p_type        integer,
  p_date        date,
  p_head_code   integer,
  p_description text,
  p_amount      numeric
)
returns public.vouchers
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_no  integer;
  v_row public.vouchers;
begin
  if coalesce(public.app_role(), '') not in ('admin', 'accountant') then
    raise exception 'not authorized' using errcode = '42501';
  end if;
  if p_amount is null or p_amount <= 0 then
    raise exception 'amount must be greater than zero' using errcode = '22023';
  end if;
  if p_date is null then
    raise exception 'voucher date is required' using errcode = '22023';
  end if;

  update public.voucher_counters
     set last_no = last_no + 1
   where voucher_type = p_type
  returning last_no into v_no;

  if v_no is null then
    raise exception 'invalid voucher type %', p_type using errcode = '22023';
  end if;

  insert into public.vouchers (voucher_type, voucher_no, voucher_date, head_code, description, amount, created_by)
  values (p_type, v_no, p_date, p_head_code, coalesce(trim(p_description), ''), p_amount, auth.uid())
  returning * into v_row;

  return v_row;
end
$$;

create function public.cancel_voucher(p_id bigint, p_reason text)
returns public.vouchers
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_row public.vouchers;
begin
  if coalesce(public.app_role(), '') <> 'admin' then
    raise exception 'not authorized' using errcode = '42501';
  end if;

  update public.vouchers
     set cancelled_at = now(), cancelled_by = auth.uid(), cancel_reason = nullif(trim(p_reason), '')
   where id = p_id and cancelled_at is null
  returning * into v_row;

  if v_row.id is null then
    raise exception 'voucher % not found or already cancelled', p_id using errcode = 'P0002';
  end if;

  return v_row;
end
$$;

-- ---------------------------------------------------------------------------
-- Privileges: nothing for anon; functions only for signed-in users
-- ---------------------------------------------------------------------------

revoke all on all tables in schema public from anon;
revoke execute on function public.app_role() from public, anon;
revoke execute on function public.handle_new_user() from public, anon, authenticated;
revoke execute on function public.create_voucher(integer, date, integer, text, numeric) from public, anon;
revoke execute on function public.cancel_voucher(bigint, text) from public, anon;
grant execute on function public.app_role() to authenticated;
grant execute on function public.create_voucher(integer, date, integer, text, numeric) to authenticated;
grant execute on function public.cancel_voucher(bigint, text) to authenticated;

-- ---------------------------------------------------------------------------
-- Row Level Security
-- ---------------------------------------------------------------------------

alter table public.company_settings enable row level security;
alter table public.account_heads    enable row level security;
alter table public.customers        enable row level security;
alter table public.vouchers         enable row level security;
alter table public.voucher_counters enable row level security;
alter table public.daybook          enable row level security;
alter table public.profiles         enable row level security;

-- company_settings: everyone active reads, admin updates
create policy company_settings_select on public.company_settings
  for select to authenticated using (public.app_role() is not null);
create policy company_settings_update on public.company_settings
  for update to authenticated using (public.app_role() = 'admin') with check (public.app_role() = 'admin');

-- account_heads: no delete (matches legacy "Not Authorized!")
create policy account_heads_select on public.account_heads
  for select to authenticated using (public.app_role() is not null);
create policy account_heads_insert on public.account_heads
  for insert to authenticated with check (public.app_role() in ('admin', 'accountant'));
create policy account_heads_update on public.account_heads
  for update to authenticated
  using (public.app_role() in ('admin', 'accountant'))
  with check (public.app_role() in ('admin', 'accountant'));

-- customers
create policy customers_select on public.customers
  for select to authenticated using (public.app_role() is not null);
create policy customers_insert on public.customers
  for insert to authenticated with check (public.app_role() in ('admin', 'accountant'));
create policy customers_update on public.customers
  for update to authenticated
  using (public.app_role() in ('admin', 'accountant'))
  with check (public.app_role() in ('admin', 'accountant'));
create policy customers_delete on public.customers
  for delete to authenticated using (public.app_role() = 'admin');

-- vouchers: read only; writes go through create_voucher / cancel_voucher
create policy vouchers_select on public.vouchers
  for select to authenticated using (public.app_role() is not null);

-- voucher_counters: no policies -> not reachable by clients

-- daybook: read all; accountants maintain manual (non-auto) rows only
create policy daybook_select on public.daybook
  for select to authenticated using (public.app_role() is not null);
create policy daybook_insert on public.daybook
  for insert to authenticated with check (public.app_role() in ('admin', 'accountant') and not is_auto);
create policy daybook_update on public.daybook
  for update to authenticated
  using (public.app_role() in ('admin', 'accountant') and not is_auto)
  with check (public.app_role() in ('admin', 'accountant') and not is_auto);
create policy daybook_delete on public.daybook
  for delete to authenticated using (public.app_role() in ('admin', 'accountant') and not is_auto);

-- profiles: users see their own; admins see and manage all
create policy profiles_select on public.profiles
  for select to authenticated using (user_id = auth.uid() or public.app_role() = 'admin');
create policy profiles_update on public.profiles
  for update to authenticated using (public.app_role() = 'admin') with check (public.app_role() = 'admin');

-- ---------------------------------------------------------------------------
-- Storage: private bucket for customer photos
-- ---------------------------------------------------------------------------

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('customer-photos', 'customer-photos', false, 2097152, array['image/jpeg', 'image/png', 'image/webp']);

create policy customer_photos_select on storage.objects
  for select to authenticated
  using (bucket_id = 'customer-photos' and public.app_role() is not null);
create policy customer_photos_insert on storage.objects
  for insert to authenticated
  with check (bucket_id = 'customer-photos' and public.app_role() in ('admin', 'accountant'));
create policy customer_photos_update on storage.objects
  for update to authenticated
  using (bucket_id = 'customer-photos' and public.app_role() in ('admin', 'accountant'));
create policy customer_photos_delete on storage.objects
  for delete to authenticated
  using (bucket_id = 'customer-photos' and public.app_role() = 'admin');
